"""add photo description

Revision ID: 9406b709bcef
Revises: da65e9b50733
Create Date: 2019-05-06 22:24:24.867694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9406b709bcef'
down_revision = 'da65e9b50733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('desc', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'desc')
    # ### end Alembic commands ###
